cs35l41: rename header to avoid upstream collision
A driver for CS35L41 was introduced upstream in commit 6450ef5590568
("ASoC: cs35l41: CS35L41 Boosted Smart Amplifier"). This generated name
collisions with this OOT driver version. While we evaluate a switch to
the upstream version, this patch renames a header file to fix several
issues of the following type:

  amplifiers/cs35l41/cs35l41-i2c.c:74:9:
  error: incomplete definition of type 'struct cs35l41_private'
        cs35l41->dev = dev;
        ~~~~~~~^
  amplifiers/cs35l41/cs35l41-i2c.c:63:9:
  note: forward declaration of 'struct cs35l41_private'
        struct cs35l41_private *cs35l41;
               ^

Bug: 215712060
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Change-Id: I0e1b276257f715445289e28ab732d7b66d3bdf21